### ISSUE TITLE
Account IDs (Alternative to sharing email addresses when sharing files)

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#104]
I like to keep the email I use for my Filen account private and not share it with anyone. Therefore, I would like to purpose having an account ID which will be generated when an account is created. This ID will be a string of numbers and letters and when you want to share a file or folder with another Filen user, they can either give you their email or their account ID.

This will increase privacy for users.

**Comment by doubletimedan** [comment]
> To further expand on this, It would be extremely good if Filen gave the _option_ for users to not use an email at all for account creation, instead adopting the randomly generated string as their account identification, similar to Mullvad's system. This allows users who want more privacy have it while still letting the majority of users use emails for convenience

As much is I like this idea there are reasons why it can be used on mullvad and not really on filen, I'll give 2 for example:

1. Mullvad can do it because you can only use the service if you pay for it so if you don't pay mullvad can just give the number you generated to someone else in the future and since filen has the option of free accounts it just wouldn't be sustainable

2. They both do different types of business, mullvad supplies a VPN which you log into once on all your devices and you don't need to worry about it again but filen as a cloud storage provider has the idea of you logging in on the web regularly which means you wouldn't want to put in a random string of numbers and letters everytime you have to log in

I know you said "option" but I think that option would be alot better put when your sharing your link to someone and you want to hide your email address rather then someone getting one of those random codes and forgetting it completely and we all know what would happen if we forget our login to our filen accounts😂

Of course I'm not an employee at filen but it doesn't seem like something they would put time in because of these reasons

P.S I typed this very quickly so if there are mistakes etc don't attack me☺️

**Comment by DanielProg39** [comment]
> Further, Filen provides the Masterkey to users meaning you can recover your filen account without the email/pass as long as you have it saved.

Really? How do I find it?

**Comment by DanielProg39** [comment]
> > Really? How do I find it?
> 
>     1. https://drive.filen.io/#/account/security
> 
>     2. ![master](https://user-images.githubusercontent.com/115472706/204050247-2b38dbb4-61e1-4ffa-96c9-18baf70a5024.png)

Thanks, I just couldn't find it in an old application
