### ISSUE TITLE
[Feature Request] Moving files to the Windows Recycle Bin when synchronizing a file deletion from the cloud to Windows

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-desktop#118]
Is it possible to move a file to the Windows Recycle Bin instead of deleting it directly when syncing deleted files from the cloud to Windows? This (deleting permanently or moving to Recycle Bin) could be made optional as a Setting (global or per Sync) in the Desktop App.

**Comment by Dwynr** [comment]
Good idea.

Implemented via https://github.com/FilenCloudDienste/filen-desktop/commit/638c63405c84c57688531bf4210f89c9d1054ef0

The client now creates separate local trash directories (hidden dot folders) for each sync location and moves delete files and folders there. Items inside the local trash will be deleted 30 days after being moved there. The user can also manually clear the local trash inside the settings.
This is a better option instead of moving deleted items to the OS's trash bin. If we would move deleted items to the OS trash bin they would be all over the place and unorganized. With the new implementation deleted items are preserved inside their original sync location.
