### ISSUE TITLE
Bring back the download, upload speed limitation option.

### ISSUE THREAD

**Issue by uncharted-user** [FilenCloudDienste/filen-desktop#118]
**Describe the bug**
The new version has no way to limit the bandwidth which is necessary during large upload or syncs.

**To Reproduce**
1. Open the app
2. Look for the bandwidth limit options

**Expected behavior**
The app should have an option to limit the upload and download speed.

**OS (please complete the following information):**
 - OS: Windows, macOS, Linux
 - App version: 3.0.34

**Comment by Dwynr** [comment]
This is not a bug. The new desktop app is based on the completely new SDK, which currently does not support and option to throttle bandwidth usage. We will bring it back, but it's not our highest priority right now.

**Comment by uncharted-user** [comment]
> This is not a bug.

Could you please add this as enhancement?

**Comment by stevenjwheeler** [comment]
> This is not a bug. The new desktop app is based on the completely new SDK, which currently does not support and option to throttle bandwidth usage. We will bring it back, but it's not our highest priority right now.

I feel like this should be a higher priority.
I'm currently trying to do a sync of a very large file structure and needing to do it at night because when Filen starts to upload, it maxes out my bandwidth and takes the whole network down with it. I simply cannot use this app properly without the option to limit bandwidth like nearly every other cloud service allows.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
