### ISSUE TITLE
Linux desktop sync incorrectly handles folder shortcuts/symbolic links

### ISSUE THREAD

**Issue by joewood9364** [FilenCloudDienste/filen-desktop#194]
When making a folder shortcut in KDE Neon filen tries to sync the target folder rather than just uploading the shortcut file itself.

**Comment by ahmuro** [comment]
It would be important to clarify which one of those two are you talking about. If it is a symbolic link then I believe syncing the folder is the correct behavior, since symlinks happen at filesystem level (not just a file with instructions to redirect) and the application targeting the files doesn't even know there's a link, it just sees the files as if they were there.
Ive never used kde that much, so I'm not sure how does it create shortcuts, if it is just a file with its own size and attributes containing instructions to a location, then yes, I think it just should be synced as is, just the single file. But if kde creates shortcuts using symlinks then that's just symlinks are and that behavior is at filesystem and kernel level.

**Comment by joewood9364** [comment]
Thanks, I'm new to Linux but I do think they are symlinks in plasma. 
I'm used to shortcut files in windows being just a file in itself, do you happen to know an equivalent in Linux?

**Comment by ahmuro** [comment]
Not completely sure but I think a desktop file is the closest to the way windows works. Not at my pc right now so can't test, but I think this should work
```
[Desktop Entry]
Name=Your shortcut name
Comment=Info as a floating tooltip
Exec=xdg-open /Path/to/your/folder
Terminal=false
Icon=Path to a .png file
Type=Application
```

**Comment by joewood9364** [comment]
Thanks for that, was also able to make a .desktop shortcut with plasma through the context menu (URL option).
