### ISSUE TITLE
[Feature request] Add Filen Sync entry in explorer sidebar

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-desktop#39]
Hi!
As ~~the slowest, GAFAM-powered and privacy-invasive~~ OneDrive does, it could be cool to make the Desktop client add a new entry to the file explorer sidebar, as you can see on this picture:

![](https://user-images.githubusercontent.com/59477313/163474242-70b6fb48-e176-447d-95a9-4f518bb8d8f7.png)

It can make access to files even more efficient for everyone!

**Comment by ahmuro** [comment]
This is absolutely needed. More options of file explorer integration would be great, but this is basic

**Comment by DanielProg39** [comment]
Yeah, it would be ideal to be implemented like in #10. Many cloud providers support virtual disk mounting. I know that it could be difficult to implement due to encryption but if you will add this feature, it would be fantastic. Cloud syncing and bacups are great but with this feature your app would become arguably the best

**Comment by ashutoshsaboo** [comment]
+1 on this request as well, this would be really great to have! The UX would become so awesome on desktop!

**Comment by Dwynr** [comment]
Duplicate, closing.
