### ISSUE TITLE
[Feature request] Add a Block-Level File Syncing

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-desktop#40]
Hi everyone!

Because in people's minds, *privacy and security doesn't match with speed*, I just wanted to share with you a more powerful file syncing method! It can save a **LOT** of time for uploads, which is the weak spot of Filen, and is named the **Block-Level File Sync**!

[If you don't know what it is, click here](https://cloudstorageinfo.org/block-level-file-sync)

I can understand that the zero-knowledge argument of Filen can explain why this method isn't used, but let me share a possible solution:
### Why not apply a block-level synchronization to the encrypted file?
Because the account owner knows the encryption key used to protect his files on the cloud, why not encrypt the file locally, like Filen does, and then start a comparison mechanism which **will extract missing data blocks of the file on the cloud to only upload them**?

_I leave this question open, because I think it's worth asking it to make this cloud storage service faster!_

**Comment by Dwynr** [comment]
Hello,

block level sync is sadly not possible since every file chunk's hash is always different due to different IV's used for encryption. The only way it would be possible is to first request the changed chunk position from our servers (+- 1 if the size changed), decrypt it locally, check if something really changed, and if something changed, re-use the key and IV and encrypt the new chunk. This is highly inefficient for large files and would consume a lot of bandwidth in the long run.

**Comment by DodoLeDev** [comment]
I understand... I thought it could be a possible way to optimize the speed of Filen uploads, that is the main drawback people said about this incredible cloud service! :sweat_smile:
