### ISSUE TITLE
Sync not properly checking for changes in metadata/ID3 tag information in audio files and updating if there's changes

### ISSUE THREAD

**Issue by godzfire** [FilenCloudDienste/filen-desktop#78]
**Describe the bug**
According to Filen support, it's a known issue that version 2.x does not properly check for changes in metadata/ID3 tag information in audio files and update if there's changes when a sync is set up.

It was stated that version 3.x corrects that, however as of the most current dev release 3.0.23, this is still not properly functioning.

**To Reproduce**
Set up a Local To Cloud sync and upload some audio files. Makes some metadata/ID3 changes to the local copy.

**Expected behavior**
Once the local changes are made, Filen should pick up the change and sync up.

**Screenshots**
None available.

**OS (please complete the following information):**
Mac OS Monterey 12.7.6 (21H1320)

**Comment by Dwynr** [comment]
Hello,

are you perhaps changing the audio metadata using Apple Music? If so, then the metadata is actually not written to the original file, but stored in Apple Music, which won't trigger a sync action since the original file remains the same. You can check it yourself by looking at the "modified" timestamp of the file using Finder. If that timestamp (and the file's hash) does not change, the client will not act. It only acts when the original file changed.
