### ISSUE TITLE
[Feature Request] Add Transparent Zstandard client side compression

### ISSUE THREAD

**Issue by ghost** [FilenCloudDienste/filen-desktop#90]
It is extremely fast to compress and decompress while also giving a good compression ratio.
It will help save storage usage for users.

**Comment by DanielProg39** [comment]
I don't think that this feature is useful as customers just want to store their original files. Cloud storage providers that use such technologies are being constantly criticized due to loss of quality or metadata loss. I am, personally, against it as I would compress my files if needed, in other cases I just want my files stored in original size, format and quality

**Comment by DanielProg39** [comment]
> It's Lossless compression
> It is also extremely fast to open, edit and save files compress in Zstandard
Well, it makes sense than. After researching a bit, I understood that it is a really great idea
